trigger:
--master

jobs:

  - job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  # The Windows build involves running a powershell script
  # to execute the Cake build script
  steps:
  - powershell: .\build.ps1
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
